# -*- coding: utf-8 -*-

from odoo import api, fields, models, exceptions
from datetime import datetime

PROGRESS_INFO = [('draft', 'Draft'), ('confirmed', 'Confirmed')]


class TimeSheetPolicy(models.Model):

    _name = 'time.sheet.policy'

    name = fields.Many2one(comodel_name='hospital.year', string='Year', required=True)
    policy = fields.Html(string='Time Sheet Policy', required=True)
    generated_by = fields.Many2one(comodel_name='res.users', string='Generated By', readonly=True)
    generated_on = fields.Date(string='Generated On', readonly=True)
    progress = fields.Selection(PROGRESS_INFO, string='Progress', default='draft')
    comment = fields.Text(string='Comment')

    # Access Function
    def check_progress_access(self):
        group_list = ['Time Manager', 'Admin']

        outer_obj = self.env['check.group.access'].browse([('id', '=', 1)])
        if not outer_obj.check_group_access(group_list):
            raise exceptions.ValidationError('Error! You are not authorised to change this record')

    @api.multi
    def trigger_confirm(self):
        self.write({'progress': 'confirmed'})

    @api.multi
    def unlink(self):
        self.check_progress_access()
        raise exceptions.ValidationError('Error! You are not authorised to delete this document')

    @api.multi
    def write(self, vals):
        self.check_progress_access()
        return super(TimeSheetPolicy, self).write(vals)

    @api.model
    def create(self, vals):
        self.check_progress_access()
        vals['generated_by'] = self.env.user.id
        vals['generated_on'] = datetime.now().strftime('%Y-%m-%d')
        return super(TimeSheetPolicy, self).create(vals)

    _sql_constraints = [
        ('duplicate_shift', 'unique (name)', "Duplicate Shift name"),
    ]

